### ISSUE TITLE
from math import *

### ISSUE THREAD

**Issue by JanKanis** [Russell91/pythonpy#42]
I actually use a similar (but much simpler) script as desktop calculator. Pythonpy has much more features over the whole but one thing I miss is everything from math being available by default. I find that very handy as a calculator replacement.

Could you add a "from math import *" line?

**Comment by abarnert** [comment]
It would be very easy to add a `--module`/`-m` option (with `store=append`) and do a `from MODULE import *` for each one. (Well, it would be very easy if you don't need to handle subpackages pre-3.3; for 2.7/3.1-3.2, you have to recursively `import_module` each package along the way, and for 2.6/3.0 and earlier you have to use `__import__` instead, which returns the top-level package instead of the module at each step…)

But I'm not sure that `alias pymath="py -mmath"` is that much better of an answer, so it may not be worth the 3 lines of code to add it.

**Comment by Russell91** [comment]
So perhaps enough people want this to justify an optional config file for pythonpy. For example, a ~/.pyrc could contain arbitrary python code that would be executed on launch. Then JanKanis would be able to get all of the math functions by just adding "from math import *" to ~/.pyrc. It seems that this would actually be a better way of adding the pyplt customization that I have in the wiki. Who knows what people would come up with. But one could also load the code from ~/.pyrc after the argparse parser object was initialized, but before it was evaluated, such that users would be able to create their own arguments as well. This would be a big feature, so I'm curious what ideas people have for it.

**Comment by abarnert** [comment]
That's a nice idea. It's also how Python and IPython handle arbitrary configuration (although they have an environment variable that lets you override the file to be loaded, and a command-line flag to ignore it; not sure if you need either of those).

Loading it after the parser exists is an interesting extension to the idea, but I'm not sure it's necessary.

You probably want to use an XDG/Mac-compliant name when relevant. I believe the usual shuffle goes something like this (ignoring Windows):

 * If the environment variable `XDG_CONFIG_HOME` exists, use `$XDG_CONFIG_HOME/.pyrc` (for modern Linux and some *BSD).
 * If not, if directory `~/Library/Application Support` exists, use `~/Library/Application Support/org.russell91.pythonpy/.pyrc` (for OS X).
 * If not, if `~/.config` exists, use `~/.config/.pyrc` (for older Linux and other *BSD).
 * Otherwise, use `~/.pyrc` (for older *nix systems).

But google it and make sure rather than relying on my memory, of course. :)

**Comment by Russell91** [comment]
Good tips on the config file. I'm starting to feel the same way I originally did on this. Command line tools should be stateless for the most part. It just feels weird that using pythonpy on two different computers could produce two different results.
