### ISSUE TITLE
Use of a generator expression with -x fails

### ISSUE THREAD

**Issue by kergoth** [Russell91/pythonpy#63]
List comprehensions do work, however:

### Works:
```
$ py -fx 'any([i in x for i in "AEI"])' <foo
```
### Fails:
```
$ py -fx 'any(i in x for i in "AEI")' <foo
Traceback (most recent call last):
  File "/Users/kergoth/.local/share/virtualenvs/pythonpy2/lib/python2.7/site-packages/pythonpy/__main__.py", line 168, in <module>
    for x in result:
  File "/Users/kergoth/.local/share/virtualenvs/pythonpy2/lib/python2.7/site-packages/pythonpy/__main__.py", line 149, in <genexpr>
    result = (x for x in stdin if eval(args.expression))
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <genexpr>
NameError: global name 'x' is not defined
```

**Comment by georgepsarakis** [comment]
It seems that this is an issue in [safe_eval](https://github.com/Russell91/pythonpy/blob/master/pythonpy/__main__.py#L139).
In order for generator expressions to work properly it requires passing x as a global not a local function variable (implicitly since calling inside the `safe_eval` function):

```python
def safe_eval(text, x):
        try:
            return eval(text, {"x": x})
        except:
            return None
```

Not thoroughly tested though.

**Comment by georgepsarakis** [comment]
This seems to work in all cases I think: 

```python 
eval('lambda x: any((i in x for i in "AEI"))')(x) 
```

**Comment by Russell91** [comment]
I've thought about this off and on for a long time now and I just don't see how to solve this issue in a nice way. The problem is that once you pass a dictionary to eval, it ignores globals(). That means you need to pass globals() anyway, but now you need to put x in globals, which is not a nice thing and was something you didn't have to worry about before. If python had efficient immutable dictionary unions, it would be a different story. Probably not the end of the world, but somehow it feels worse than just treating this as a known bug. Others have found this issue here as well: http://stackoverflow.com/questions/11669379/undefined-global-in-list-generator-expression-using-python3-works-with-python2.
