### ISSUE TITLE
Avoid using "sudo pip" for installation

### ISSUE THREAD

**Issue by LazyGetter** [Russell91/pythonpy#75]
The instructions for installation suggest using "sudo pip" . OS X El Capitan will display a warning when doing so. For details : [OSX El Capitan: sudo pip install OSError:](http://stackoverflow.com/questions/33004708/osx-el-capitan-sudo-pip-install-oserror-errno-1-operation-not-permitted/33004920#33004920)

**Comment by Russell91** [comment]
Okay, historically that was there because pythonpy would try to automatically install it's bash completion to /etc/bash_completion.d. But this has been so sketch for cross platform compatibility that I've revised how that is done and now one has a normal pip install without sudo. `source $(find_pycompleter.py)` will allow separate adding of bash completion if that is desired.
